{{- range $componentName, $component := .Values.components -}}
  {{- if and (eq $component.type "consumer") (hasKey $component "keda") }}
    {{- $name := include "component.name" (dict "name" $componentName "Release" $.Release) }}
    {{- $kubeLabels := (merge (dict "name" $.Release.Name "instance" (printf "%s-%d" $name $.Release.Revision) "component" $componentName) $.Values.global.metadata) }}
    {{- range $i, $trigger := $component.keda.triggers }}
      {{- if and (eq $trigger.type "aws-sqs-queue") (ne (default "operator" $trigger.identityOwner) "operator") (ne $trigger.triggerAuthEnabled false) }}
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ $name }}-auth-{{ $i }}
  labels:
    {{ include "cookielab.kubernetes.labels" $kubeLabels | indent 4 | trim }}
spec:
  podIdentity:
    provider: aws
      {{- else if and (eq $trigger.type "postgresql") (or $trigger.connectionFromSecret $trigger.passwordFromSecret) }}
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ $name }}-auth-{{ $i }}
  labels:
    {{ include "cookielab.kubernetes.labels" $kubeLabels | indent 4 | trim }}
spec:
  secretTargetRef:
        {{- with $trigger.connectionFromSecret }}
    - parameter: connection
      name: {{ .name | quote }}
      key: {{ .key | quote }}
        {{- end }}
        {{- with $trigger.passwordFromSecret }}
    - parameter: password
      name: {{ .name | quote }}
      key: {{ .key | quote }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
